version: '3'
services:
  quotes_api:
    build: .
    volumes:
      - ./web:/var/www/html/quotes
    ports:
      - 8081:8081
      - 3000:3000
  quotes_database:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5434:5432